# Generated by Django 4.1.3 on 2023-01-14 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=50)),
                ('baddress', models.CharField(max_length=200)),
                ('bphone', models.IntegerField()),
                ('bdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media/')),
                ('name', models.CharField(max_length=100)),
                ('infor', models.CharField(max_length=500)),
                ('price', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField(auto_now=True, null=True)),
                ('datetime_update', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(default='nam banh boi', max_length=50)),
                ('saddress', models.CharField(default='thai binh', max_length=200)),
                ('sphone', models.IntegerField(default='235273')),
                ('sdate', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
